### ISSUE TITLE
Take part in GSoD 

### ISSUE THREAD

**Issue by Dishebh** [electron/season-of-docs-2019#2]
Hi, I would like to contribute to the `Contributor Documentation Section` project idea for GSoD this year. Can anyone tell where and how should I get started with this? 

Thanks!

**Comment by erickzhao** [comment]
Hey @Dishebh,

Thanks for reaching out! You would first have to come up with a [proposal](https://developers.google.com/season-of-docs/docs/tech-writer-application-hints) to submit to the Season of Docs program. I think you have until July 9 to submit your proposal.

In the month of July, we'll be reviewing all proposals and accepting a single one to collaborate with for three months. During the proposal selection phase, we'll be evaluating your language skills and taking into account previous technical writing experience and the quality of your proposal document.

If you're interested in the Contributor documentation, you can start by reviewing our existing contributing docs over at https://www.electronjs.org/docs/development/build-instructions-gn. Shoot us an email at `season-of-docs [at] electronjs.org` and we'll send you an invite to a Slack channel for any questions you might have about the build process, as it's a bit difficult to gather as a newcomer to the project.
